### ISSUE TITLE
Merge with upstream arc?

### ISSUE THREAD

**Issue by NicoHood** [mervick/arc-dark-software-center#2]
Hi,
I am NicoHood, one of the current two maintainers of the arc-theme soft fork. The fork can be reached here:
https://github.com/NicoHood/arc-theme

Is there any reason why this software center modification was outsourced as additional repository/software and not included directly into the official arc theme?

cc @fossfreedom

**Comment by mervick** [comment]
It was not outsourced.
Arc provide 3 themes, and only one of them has full dark colors - Arc-dark,
this repo provide styles only for Arc-dark but it will wrong to install it with Arc package by default,
because it will makes issues for other 2 themes: Arc-darkness and Arc

**Comment by NicoHood** [comment]
And why dont we add those features to the arc-dark package only then?

**Comment by mervick** [comment]
As I know arc-theme installs 3 themes at ones, I don't see anywhere separated arc-dark theme

**Comment by NicoHood** [comment]
Alright so your aim is to always have a dark software center unrelated to which theme is selected. No need to merge it then.
